// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tuchlxzgsgsgeiqmclcq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR1Y2hseHpnc2dzZ2VpcW1jbGNxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk3MjY1NDcsImV4cCI6MjA4NTMwMjU0N30.qXDxKb8JosOV4gQj-bd6GmAAT5NciwYToFYG9fhhfds";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});